version: '3'

services:
    mysql:
        image: mysql:5.7.28
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks: 
      - backend-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment: 
            - PMA_ARBITRATY=1
        ports: 
            - 8180:81
        volumes:
            - 


    wordpress:
        image: wordpress:5.3.2-php7.2-apache
        environment: 
            - WORDPRESS_DB_HOST=mysql
            - WORDPRESS_DB_USER=user
            - WORDPRESS_DB_PASSWORD=root
            - WORDPRESS_DB_NAME=database
        
        ports:
            - 8180:81
        


volumes:

networks:
    frontend-network:
    backend-network: